curl -iX POST \
  'http://localhost:8070/ngsi10/updateContext' \
-H 'Content-Type: application/json' \
-d '
{
        "contextElements": [
        {
                "entityId":{
                        "id":"peoplecounter",
                        "type":"Operator"
                },
                "attributes":[
                {
                        "name":"designboard",
                        "type":"object",
                        "value":{
                        }
                },
                {
                        "name":"operator",
                        "type":"object",
                        "value":{
                                "description":"",
                                "name":"peoplecounter",
                                "parameters":[

                                ]
                        }
                }
                ],
                "domainMetadata":[
                {
                        "name":"location",
                        "type":"global",
                        "value":"global"
                }
                ]
        },
        {
                   "entityId":{
                          "id":"lrsb/peoplecounter:latest",
                          "type":"DockerImage"
                   },
                   "attributes":[
                          {
                                 "name":"image",
                                 "type":"string",
                                 "value":"lrsb/peoplecounter"
                          },
                          {
                                 "name":"tag",
                                 "type":"string",
                                 "value":"latest"
                          },
                          {
                                 "name":"hwType",
                                 "type":"string",
                                 "value":"X86"
                          },
                          {
                                 "name":"osType",
                                 "type":"string",
                                 "value":"Linux"
                          },
                          {
                                 "name":"operator",
                                 "type":"string",
                                 "value":"peoplecounter"
                          },
                          {
                                 "name":"prefetched",
                                 "type":"boolean",
                                 "value":true
                          }
                   ],
                   "domainMetadata":[
                          {
                                 "name":"operator",
                                 "type":"string",
                                 "value":"peoplecounter"
                          },
                          {
                                 "name":"location",
                                 "type":"global",
                                 "value":"global"
                          }
                   ]
                }
        ],
"updateAction": "UPDATE"
}'


curl -iX POST \
          'http://localhost:8070/ngsi10/updateContext' \
        -H 'Content-Type: application/json' \
        -d '
        {
                "contextElements": [
                        {
                           "entityId":{
                              "id":"peoplecounter",
                              "type":"Operator"
                           },
                           "attributes":[
                              {
                                 "name":"designboard",
                                 "type":"object",
                                 "value":{
                                    "blocks":[
                                       {
                                          "id":1,
                                          "module":null,
                                          "type":"Parameter",
                                          "values":{
                                             "name":"myport",
                                             "values":[
                                                "8080"
                                             ]
                                          },
                                          "x":-425,
                                          "y":-158
                                       },
                                       {
                                          "id":2,
                                          "module":null,
                                          "type":"Parameter",
                                          "values":{
                                            "name":"service_port",
                                            "values":[
                                                "8080"
                                             ]
                                          },
                                          "x":-393,
                                          "y":-51
                                       },
                                       {
                                          "id":3,
                                          "module":null,
                                          "type":"Operator",
                                          "values":{
                                             "description":"",
                                             "name":"peoplecounter"
                                          },
                                          "x":-186,
                                          "y":-69
                                       }
                                    ],
                                    "edges":[
                                       {
                                          "block1":2,
                                          "block2":3,
                                          "connector1":[
                                             "parameter",
                                             "output"
                                          ],
                                          "connector2":[
                                             "parameters",
                                             "input"
                                          ],
                                          "id":1
                                       },
                                       {
                                          "block1":1,
                                          "block2":3,
                                          "connector1":[
                                             "parameter",
                                             "output"
                                          ],
                                          "connector2":[
                                             "parameters",
                                             "input"
                                          ],
                                          "id":2
                                       }
                                    ]
                                 }
                              },
                              {
                                 "name":"operator",
                                 "type":"object",
                                 "value":{
                                    "description":"",
                                    "name":"peoplecounter",
                                    "parameters":[
                                       {
                                          "name":"service_port",
                                          "values":[
                                             "7896"
                                          ]
                                       },
                                       {
                                          "name":"service_port",
                                          "values":[
                                             "4041"
                                         ]
                                       }
                                    ]
                                 }
                              }
                           ],
                           "domainMetadata":[
                              {
                                 "name":"location",
                                 "type":"global",
                                 "value":"global"
                              }
                           ]
                        }
                ],
        "updateAction": "UPDATE"
        }'


